name = 'ailodi-v2'
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "./out"
not_found_handling = "single-page-application"

[env.production]
name = "ai-lodi-blog-v2"

[env.preview]
name = "ai-lodi-blog-v2-preview"